### PR TITLE
Configurable comments in kiwi schema

### PR DESCRIPTION
**Pull request by jgleissner**
Implement support for adding comments to generated kiwi schema.
Change all existing arch and build flavor config to schema comments.
Add OBS-IgnorePackage: rpm comment (https://github.com/SUSE-Enceladus/keg-recipes/issues/38).

### CODE REVIEW

**Review by rjschwei — APPROVED** [review]
`schema-comments` should probably be `image-config-comments` since keg does not generate a schema.

**Comment by jgleissner** [comment]
> `schema-comments` should probably be `image-config-comments` since keg does not generate a schema.

I was unsure about the name. What we include now is really build configuration (why OBS needs this to be in `config.kiwi` is perhaps another topic), so not actually image config data. But then the comments could be anything, even just informal ones. So I settled on `schema-comments` because it's comments that get injected into the schema. I'm open to better a better name, of course.

**Comment by rjschwei** [comment]
> > `schema-comments` should probably be `image-config-comments` since keg does not generate a schema.
> 
> I was unsure about the name. What we include now is really build configuration (why OBS needs this to be in `config.kiwi` is perhaps another topic), so not actually image config data. But then the comments could be anything, even just informal ones. So I settled on `schema-comments` because it's comments that get injected into the schema. I'm open to better a better name, of course.

But `kiwi.config` is not a `schema` that's what I think makes things a bit weird looking/reading. And `image-config-comments` is generic enough to express that it could be anything. But I am alos fine leaving he name. I'll get over it.

**Comment by jgleissner** [comment]
Initially was using `kiwi-comments`, as it appears in the kiwi file (I don't think there's an established term for config.kiwi except "the kiwi file"). I can change it to `image-config-comments`, no problem.

**Pull request merged**
