### PR TITLE
drop containerd-ctr and klogd (bsc#1199241)

### PR DESCRIPTION
**Pull request by jgleissner**
Drop unsupported containerd-ctr from CHOST images.
Drop obsolete and unreleased klogd from all images.

### CODE REVIEW

**Comment by rjschwei** [comment]
Nothing gets removed from CHOST without customer consultation.

**Comment by jgleissner** [comment]
Any update on this? Should I change the PR to remove only klog?

**Comment by rjschwei** [comment]
> Any update on this? Should I change the PR to remove only klog?

Yes

**Comment by jgleissner** [comment]
Changed to remove klogd only.

**Review by rjschwei — APPROVED** [review]

**Pull request merged**
