### PR TITLE
Adjust hardening for some SAP requirements

### LINKED ISSUE #149: remediation for SAP images needs updating
QA testing of SAP on the hardened images found tha some of the remediations are incompatible with SAP.

To correct we need to:

1: remove pam_apparmor from the list of installed packages for sap hardened images
2: hardening script for sap hardening loses the line
/usr/bin/bash -e /usr/share/scap-security-guide/bash/sle15-script-pcs-hardening.sh

and gets:
```
HARDENING_RULES=" \
xccdf_org.ssgproject.content_rule_aide_check_audit_tools \
xccdf_org.ssgproject.content_rule_aide_periodic_cron_checking \
xccdf_org.ssgproject.content_rule_aide_verify_acls \
xccdf_org.ssgproject.content_rule_aide_verify_ext_attributes \
xccdf_org.ssgproject.content_rule_sudo_add_use_pty \
xccdf_org.ssgproject.content_rule_sudo_custom_logfile \
xccdf_org.ssgproject.content_rule_ensure_gpgcheck_globally_activated \
xccdf_org.ssgproject.content_rule_banner_etc_issue \
xccdf_org.ssgproject.content_rule_banner_etc_motd \
xccdf_org.ssgproject.content_rule_file_groupowner_etc_issue \
xccdf_org.ssgproject.content_rule_file_owner_etc_issue \
xccdf_org.ssgproject.content_rule_display_login_attempts \
xccdf_org.ssgproject.content_rule_pam_disable_automatic_configuration \
xccdf_org.ssgproject.content_rule_accounts_password_pam_pwhistory_remember \
xccdf_org.ssgproject.content_rule_accounts_passwords_pam_faildelay_delay \
xccdf_org.ssgproject.content_rule_accounts_passwords_pam_tally2 \
xccdf_org.ssgproject.content_rule_cracklib_accounts_password_pam_dcredit \
xccdf_org.ssgproject.content_rule_cracklib_accounts_password_pam_difok \
xccdf_org.ssgproject.content_rule_cracklib_accounts_password_pam_lcredit \
xccdf_org.ssgproject.content_rule_cracklib_accounts_password_pam_minlen \
xccdf_org.ssgproject.content_rule_cracklib_accounts_password_pam_ocredit \
xccdf_org.ssgproject.content_rule_cracklib_accounts_password_pam_retry \
xccdf_org.ssgproject.content_rule_cracklib_accounts_password_pam_ucredit \
xccdf_org.ssgproject.content_rule_set_password_hashing_algorithm_commonauth \
xccdf_org.ssgproject.content_rule_set_password_hashing_algorithm_systemauth \
xccdf_org.ssgproject.content_rule_disable_ctrlaltdel_burstaction \
xccdf_org.ssgproject.content_rule_smartcard_configure_ca \
xccdf_org.ssgproject.content_rule_smartcard_configure_cert_checking \
xccdf_org.ssgproject.content_rule_account_disable_post_pw_expiration \
xccdf_org.ssgproject.content_rule_accounts_maximum_age_login_defs \
xccdf_org.ssgproject.content_rule_accounts_minimum_age_login_defs \
xccdf_org.ssgproject.content_rule_accounts_password_set_max_life_existing \
xccdf_org.ssgproject.content_rule_accounts_password_set_min_life_existing \
xccdf_org.ssgproject.content_rule_no_direct_root_logins \
xccdf_org.ssgproject.content_rule_accounts_have_homedir_login_defs \
xccdf_org.ssgproject.content_rule_accounts_tmout \
xccdf_org.ssgproject.content_rule_file_permissions_home_directories \
xccdf_org.ssgproject.content_rule_audit_rules_enable_syscall_auditing \
xccdf_org.ssgproject.content_rule_audit_rules_immutable \
xccdf_org.ssgproject.content_rule_audit_rules_mac_modification \
xccdf_org.ssgproject.content_rule_audit_rules_media_export \
xccdf_org.ssgproject.content_rule_audit_rules_networkconfig_modification \
xccdf_org.ssgproject.content_rule_audit_rules_session_events \
xccdf_org.ssgproject.content_rule_audit_rules_session_events_btmp \
xccdf_org.ssgproject.content_rule_audit_rules_session_events_utmp \
xccdf_org.ssgproject.content_rule_audit_rules_session_events_wtmp \
xccdf_org.ssgproject.content_rule_audit_rules_suid_privilege_function \
xccdf_org.ssgproject.content_rule_audit_rules_sysadmin_actions \
xccdf_org.ssgproject.content_rule_audit_rules_usergroup_modification_group \
xccdf_org.ssgproject.content_rule_audit_rules_usergroup_modification_gshadow \
xccdf_org.ssgproject.content_rule_audit_rules_usergroup_modification_opasswd \
xccdf_org.ssgproject.content_rule_audit_rules_usergroup_modification_passwd \
xccdf_org.ssgproject.content_rule_audit_rules_usergroup_modification_shadow \
xccdf_org.ssgproject.content_rule_audit_rules_dac_modification_chmod \
xccdf_org.ssgproject.content_rule_audit_rules_dac_modification_chown \
xccdf_org.ssgproject.content_rule_audit_rules_dac_modification_fchmod \
xccdf_org.ssgproject.content_rule_audit_rules_dac_modification_fchmodat \
xccdf_org.ssgproject.content_rule_audit_rules_dac_modification_fchown \
xccdf_org.ssgproject.content_rule_audit_rules_dac_modification_fchownat \
xccdf_org.ssgproject.content_rule_audit_rules_dac_modification_fremovexattr \
xccdf_org.ssgproject.content_rule_audit_rules_dac_modification_fsetxattr \
xccdf_org.ssgproject.content_rule_audit_rules_dac_modification_lchown \
xccdf_org.ssgproject.content_rule_audit_rules_dac_modification_lremovexattr \
xccdf_org.ssgproject.content_rule_audit_rules_dac_modification_lsetxattr \
xccdf_org.ssgproject.content_rule_audit_rules_dac_modification_removexattr \
xccdf_org.ssgproject.content_rule_audit_rules_dac_modification_setxattr \
xccdf_org.ssgproject.content_rule_audit_rules_dac_modification_umount \
xccdf_org.ssgproject.content_rule_audit_rules_dac_modification_umount2 \
xccdf_org.ssgproject.content_rule_audit_rules_execution_chacl \
xccdf_org.ssgproject.content_rule_audit_rules_execution_chmod \
xccdf_org.ssgproject.content_rule_audit_rules_execution_setfacl \
xccdf_org.ssgproject.content_rule_audit_rules_execution_chcon \
xccdf_org.ssgproject.content_rule_audit_rules_execution_rm \
xccdf_org.ssgproject.content_rule_audit_rules_file_deletion_events_rename \
xccdf_org.ssgproject.content_rule_audit_rules_file_deletion_events_renameat \
xccdf_org.ssgproject.content_rule_audit_rules_file_deletion_events_unlink \
xccdf_org.ssgproject.content_rule_audit_rules_file_deletion_events_unlinkat \
xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_creat \
xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_ftruncate \
xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_open \
xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_open_by_handle_at \
xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_openat \
xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_rename \
xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_renameat \
xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_renameat2 \
xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_truncate \
xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_unlink \
xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_unlinkat \
xccdf_org.ssgproject.content_rule_audit_rules_kernel_module_loading_delete \
xccdf_org.ssgproject.content_rule_audit_rules_kernel_module_loading_finit \
xccdf_org.ssgproject.content_rule_audit_rules_kernel_module_loading_init \
xccdf_org.ssgproject.content_rule_audit_rules_login_events_faillock \
xccdf_org.ssgproject.content_rule_audit_rules_login_events_lastlog \
xccdf_org.ssgproject.content_rule_audit_rules_login_events_tallylog \
xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_chage \
xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_chfn \
xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_chsh \
xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_crontab \
xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_gpasswd \
xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_insmod \
xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_kmod \
xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_modprobe \
xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_newgrp \
xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_pam_timestamp_check \
xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_passmass \
xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_passwd \
xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_rmmod \
xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_ssh_agent \
xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_ssh_keysign \
xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_su \
xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_sudo \
xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_sudoedit \
xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_unix2_chkpwd \
xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_unix_chkpwd \
xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_usermod \
xccdf_org.ssgproject.content_rule_audit_rules_time_adjtimex \
xccdf_org.ssgproject.content_rule_audit_rules_time_clock_settime \
xccdf_org.ssgproject.content_rule_audit_rules_time_settimeofday \
xccdf_org.ssgproject.content_rule_audit_rules_time_stime \
xccdf_org.ssgproject.content_rule_audit_rules_time_watch_localtime \
xccdf_org.ssgproject.content_rule_auditd_audispd_encrypt_sent_records \
xccdf_org.ssgproject.content_rule_auditd_data_disk_full_action \
xccdf_org.ssgproject.content_rule_auditd_data_retention_admin_space_left_action \
xccdf_org.ssgproject.content_rule_auditd_data_retention_max_log_file_action \
xccdf_org.ssgproject.content_rule_auditd_data_retention_space_left \
xccdf_org.ssgproject.content_rule_auditd_data_retention_space_left_action \
xccdf_org.ssgproject.content_rule_journald_compress \
xccdf_org.ssgproject.content_rule_journald_storage \
xccdf_org.ssgproject.content_rule_ensure_logrotate_activated \
xccdf_org.ssgproject.content_rule_kernel_module_dccp_disabled \
xccdf_org.ssgproject.content_rule_kernel_module_sctp_disabled \
xccdf_org.ssgproject.content_rule_file_etc_security_opasswd \
xccdf_org.ssgproject.content_rule_file_permissions_backup_etc_shadow \
xccdf_org.ssgproject.content_rule_file_permissions_etc_shadow \
xccdf_org.ssgproject.content_rule_file_groupownership_system_commands_dirs \
xccdf_org.ssgproject.content_rule_kernel_module_squashfs_disabled \
xccdf_org.ssgproject.content_rule_kernel_module_udf_disabled \
xccdf_org.ssgproject.content_rule_kernel_module_usb-storage_disabled \
xccdf_org.ssgproject.content_rule_disable_users_coredumps \
xccdf_org.ssgproject.content_rule_file_permissions_cron_d \
xccdf_org.ssgproject.content_rule_file_permissions_cron_daily \
xccdf_org.ssgproject.content_rule_file_permissions_cron_hourly \
xccdf_org.ssgproject.content_rule_file_permissions_cron_monthly \
xccdf_org.ssgproject.content_rule_file_permissions_cron_weekly \
xccdf_org.ssgproject.content_rule_chronyd_run_as_chrony_user \
xccdf_org.ssgproject.content_rule_file_permissions_sshd_config \
xccdf_org.ssgproject.content_rule_sshd_set_keepalive_0 \
xccdf_org.ssgproject.content_rule_sshd_set_idle_timeout \
xccdf_org.ssgproject.content_rule_sshd_disable_tcp_forwarding \
xccdf_org.ssgproject.content_rule_sshd_disable_user_known_hosts \
xccdf_org.ssgproject.content_rule_sshd_disable_x11_forwarding \
xccdf_org.ssgproject.content_rule_sshd_enable_warning_banner \
xccdf_org.ssgproject.content_rule_sshd_set_login_grace_time \
xccdf_org.ssgproject.content_rule_sshd_set_loglevel_verbose \
xccdf_org.ssgproject.content_rule_sshd_set_max_sessions \
xccdf_org.ssgproject.content_rule_sshd_set_maxstartups \
xccdf_org.ssgproject.content_rule_sshd_use_approved_ciphers_ordered_stig \
xccdf_org.ssgproject.content_rule_sshd_use_approved_macs \
xccdf_org.ssgproject.content_rule_sshd_use_approved_macs_ordered_stig \
"
# remediate selected rules.
for RULE in ${HARDENING_RULES}; do
    oscap xccdf eval --remediate --profile pcs-hardening  --rule ${RULE}  /usr/share/xml/scap/ssg/content/ssg-sle15-ds.xml || {
	echo "!!!FAILED: ${RULE}"
	/bin/fail
	}
done
```
https://github.com/SUSE-Enceladus/keg-recipes/tree/sap-hardening represents our initial thoughts on how to do this.

### PR DESCRIPTION
**Pull request by KeithMnemonic**
This PR splits out the sap hardened image to allow for the removal of pam_apparmor and the skipping of certain remediation steps.  To accomplish handling of pam_apparmor, a new 'hardened base' packages.yml was added that contains the packages that are common to both SAP and the standard (non SAP) BYOS hardened images. The existing sle15 (now non SAP) packages.yml was modified to only include pam_apparmor. 

Additionally, a new script, pcs-sap-hardening.sh is added. This script is only added to the config.sh  for the SAP hardened images and replaces the prior script. For the non SAP BYOS image, the existing method remains unchanged.

closes #149

### CODE REVIEW

**Comment by jeremy-moffitt** [comment]
To my understanding this addresses https://github.com/SUSE-Enceladus/keg-recipes/issues/149

**Comment by brett060102** [comment]
Changes look good to me, but I am hardly qualified.

**Comment by jgleissner** [comment]
I'm not a fan of creating different paths under `data/base/sle/hardened`. It's already a bit convoluted there and it deviates from the general scheme. Which admittedly the `hardened` subdir already does to some degree. We generally use `<category>/<module>/<sle-ver>[/<sp>]` as the path for data modules, with `module` potentially having sub-modules for specific settings (mostly used for product specific settings in the `csp` tree). `<sle-ver>` and `<sp>` are configured as include-paths in the image definition so version specific bits get pulled in automatically without having to fiddle with the image content definition. `hardened` is a bit special because instead of a separate data module we added it as a sub-module but without including it directly in the image definition but via the `include-paths` directive. This lets us re-use the image content definition of plain SLES. Maybe that's a bit confusing, not sure.

Anyhow, `data/base/sle` is supposed to be the module for all SLE based products (i.e. everything except CHOST and Micro). Instead of creating product specific sub trees, I'd suggest simply adding the product specific bits under `data/products`. That means, leave `data/base/sle/hardened` as it was except for removing `pam_apparmor` from the package list. Add `pam_apparmor` under `data/products/sles/hardened/sle15`. Add `pcs-sap-hardening` under `data/products/sap/hardened/sle15`. No changes to the image definitions required.

**Review by rjschwei — APPROVED** [review]

**Comment by KeithMnemonic** [comment]
> I'm not a fan of creating different paths under `data/base/sle/hardened`. It's already a bit convoluted there and it deviates from the general scheme. Which admittedly the `hardened` subdir already does to some degree. We generally use `<category>/<module>/<sle-ver>[/<sp>]` as the path for data modules, with `module` potentially having sub-modules for specific settings (mostly used for product specific settings in the `csp` tree). `<sle-ver>` and `<sp>` are configured as include-paths in the image definition so version specific bits get pulled in automatically without having to fiddle with the image content definition. `hardened` is a bit special because instead of a separate data module we added it as a sub-module but without including it directly in the image definition but via the `include-paths` directive. This lets us re-use the image content definition of plain SLES. Maybe that's a bit confusing, not sure.
> 
> Anyhow, `data/base/sle` is supposed to be the module for all SLE based products (i.e. everything except CHOST and Micro). Instead of creating product specific sub trees, I'd suggest simply adding the product specific bits under `data/products`. That means, leave `data/base/sle/hardened` as it was except for removing `pam_apparmor` from the package list. Add `pam_apparmor` under `data/products/sles/hardened/sle15`. Add `pcs-sap-hardening` under `data/products/sap/hardened/sle15`. No changes to the image definitions required.

@jgleissner  Please re-review as I believe I have this implemented per above now.

**Review by jgleissner — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
