### PR TITLE
Fix btrfs grub subvolumes for aarch64

### PR DESCRIPTION
**Pull request by jgleissner**
Add architecture specific profiles to all SLE Micro 5.3 flavors. Add architecture specific btrfs subvolumes for grub.

### CODE REVIEW

**Comment by rjschwei** [comment]
Visually that looks correct, can you please generate a description for testing from this and stick it into the :ModifiedTestImages project so we can run some tests before we merge? Thanks.

**Comment by jgleissner** [comment]
> Visually that looks correct, can you please generate a description for testing from this and stick it into the :ModifiedTestImages project so we can run some tests before we merge? Thanks.

Done.

**Comment by jgleissner** [comment]
@rjschwei  Should we merge this before merging into `released`? I gave the image a smoke test and it looked fine.

**Review by rjschwei — APPROVED** [review]

**Comment by rjschwei** [comment]
Thanks for testing. Merging

**Pull request merged**
